# Quick and dirty stuff just for testing

name: Push to meta repo

on:
    push:
        branches: [main]
    workflow_dispatch:
        inputs:
            debug:
                type: boolean
                description: "Enable debug logging"
                default: false
    schedule:
        - cron: "0 * * * *"

jobs:
    run:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              env:
                  LAST_COMMIT: ${{ github.event.head_commit.message }}
            - name: Checkout output repo
              uses: actions/checkout@v4
              with:
                  repository: MCSRLauncher/meta
                  token: ${{ secrets.META_TOKEN }}
                  path: run
            - uses: oven-sh/setup-bun@v2
            - run: bun install --production --frozen-lockfile
            - name: Generate
              env:
                  PINO_LOG_LEVEL: ${{ github.event.inputs.debug == 'true' && 'debug' || '' }}
              run: bun start all --minify | bun pino-pretty
            - name: Push
              run: |
                  cd run
                  git config user.email "mcsrlauncher@gmail.com"
                  git config user.name "MCSRLauncher"

                  git add .

                  if git diff --quiet; then
                      echo "No changes detected."
                      exit 0
                  fi

                  echo "output/index.json changed — pushing."
                  git add .

                  CHANGED_FILES=$(git diff --name-only)

                  # output/index.json이 변경된 경우에만 push
                  if echo "$CHANGED_FILES" | grep -qx 'output/index.json'; then
                      git commit -m "Update - $(date +'%Y-%m-%d')"
                      git push
                  else
                      echo "output/index.json not changed — skipping push."
                  fi
