# Quick and dirty stuff just for testing

name: Push to test repo

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        env:
          LAST_COMMIT: ${{ github.event.head_commit.message }}
      - name: Checkout output repo
        uses: actions/checkout@v4
        with:
          repository: TheKodeToad/metabolism-test
          token: ${{ secrets.PAT }}
          path: run
      - uses: oven-sh/setup-bun@v2
      - run: bun install --production --frozen-lockfile
      - name: Generate
        run: env PINO_LOG_LEVEL=debug bun start all | bun pino-pretty
      - name: Push
        run: |
          cd run
          git config user.email "gitbot@scrumplex.net"
          git config user.name "PrismAutomata"
          git add .
          git diff-index --quiet HEAD || git commit -m "Automatic update for latest commit
          ${{ github.event.head_commit.message }}"
          git push
